project:
  type: website
  output-dir: docs

website:
  title: "USyd NCI Gadi User Guide"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/00_gadi_access.html
        text: "Access Gadi"
      - href: notebooks/01_setup.html
        text: "Set up your computer"
      - text: "Introduction to Gadi"
        menu: 
        - text: "System offerings"
          href: notebooks/02_system.html
        - text: "Infrastructure expectations"
          href: notebooks/03_expectations.html
      - text: "Working on Gadi"
        menu: 
        - text: "Navigating the system"
          href: notebooks/04_system.html
        - text: "Transferring data"
          href: notebooks/05_data_transfer.html
        - text: "Accounting"
          href: notebooks/06_accounting.html
        - text: "Specialised environments"
          href: notebooks/07_environments.html
      - text: "Running a job"
        menu:
        - text: "Job scripts and submission"
          href: notebooks/08_job_script.html
        - text: "Job monitoring"
          href: notebooks/09_job_monitoring.html
        - text: "Resource efficiency"
          href: notebooks/10_job_efficiency.html

  cookie-consent: 
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
    theme: simplex
    css: [lesson.css, bootstrap-icons.css]
    toc: true
    code-overflow: wrap
    highlight-style: github


