project:
  type: website
  output-dir: docs

website:
  title: "USyd NCI Gadi User Guide"
  site-url: https://sydney-informatics-hub.github.io/
  navbar:
    logo: fig/usyd-logo.png
  sidebar:
    style: "docked"
    background: white
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Introduction to Gadi"
        contents: 
        - text: "Introduction to HPC"
          href: notebooks/02_intro_hpc.html
        - text: "Gadi overview"
          href: notebooks/02_system_setup.html
        - text: "Infrastructure expectations"
          href: notebooks/03_expectations.html
      - href: notebooks/00_gadi_access.html
        text: "Access Gadi"
      - href: notebooks/01_setup.html
        text: "Set up your computer"
      - section: "Working on Gadi"
        contents: 
        - text: "Command line"
          href: notebooks/04_command_line.html
        - text: "Data transfer"
          href: notebooks/05_data_transfer.html
        - text: "Software"
          href: notebooks/11_software.html
        - text: "Accounting"
          href: notebooks/06_accounting.html
      - section: "Running a job"
        contents:
        - text: "Job scripts and submission"
          href: notebooks/08_job_script.html
        - text: "Working within walltime"
          href: notebooks/12_walltime.html          
        - text: "Job monitoring"
          href: notebooks/09_job_monitoring.html
        - text: "Benchmarking and efficiency"
          href: notebooks/10_job_efficiency.html
        - text: "Parallel jobs"
          href: notebooks/13_parallel_jobs.html          
      - href: support.qmd
        text: Support and resources

  cookie-consent: 
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
    link-external-newwindow: true
    link-external-icon: true # displays an icon next to external links
    theme: cosmo
    css: [lesson.css, bootstrap-icons.css]
    toc: true
    code-overflow: wrap
    highlight-style: github


